version: "3.2"
services:
    php-apache:
        image: ${PROJECT_PREFIX}-php-apache
        build:
            context: './apache'
            args:
                PHP_VERSION: ${PHP_VERSION}
        networks:
            - backend
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
          #  - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        ports:
            - "80:80"
            - "443:443"
        container_name: php-${PHP_VERSION}
        links:
            - mysql

    mysql:
        image: ${PROJECT_PREFIX}-mysql
        build:
            context: './mysql'
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./data:/var/lib/mysql/
        networks:
            - backend
        # The default MySQL installation only creates the "root" administrative account
        # create new users using docker-compose exec
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        container_name: mysql-${MYSQL_VERSION}
#    phpmyadmin:
#        depends_on:
#            - mysql
#        links:
#            - mysql
#        image: phpmyadmin/phpmyadmin
#        restart: always
#        ports:
#            - '8081:80'
#        environment:
#            PMA_HOST: mysql
#            MYSQL_USERNAME: "${DB_USERNAME}"
#            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#        networks:
#            - backend
#        volumes:
#            - /sessions
#        container_name: phpmyadmin
networks:
    frontend:
    backend:
#volumes:
#    mysql_data: